FROM wordpress:7.0.2

RUN apt-get update && apt-get install -y --no-install-recommends \
    less \
    default-mysql-client \
    && curl -o /usr/local/bin/wp -SL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x /usr/local/bin/wp \
    && wp --info --allow-root \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
